metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
- add_cloud_metadata:

output.elasticsearch:
  hosts: ['elasticsearch:9200']
  protocol: "https"
  username: elastic
  # Read PW from metricbeat.keystore
  password: "${ELASTIC_PASSWORD}"
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

setup.kibana:
  host: "http://kibana:5601"
  username: elastic
  password: "${ELASTIC_PASSWORD}"
  protocol: "http"
  ssl.enabled: false
  ssl.certificate_authorities: ["/usr/share/metricbeat/certs/ca/ca.crt"]

xpack.monitoring.enabled: true

metricbeat.modules:
#------------------------------- Docker Module -------------------------------
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "image", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 10s

  # To connect to Docker over TLS you must specify a client and CA certificate.
  #ssl:
    #certificate_authority: "/usr/share/metricbeat/certs/ca/ca.crt"
    #certificate:           "/usr/share/metricbeat/config/certs/metricbeat/metricbeat.crt"
    #key:                   "/usr/share/metricbeat/config/certs/metricbeat/metricbeat.key"

- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - process         # Per process metrics
    - process_summary # Process summary
    - uptime          # System Uptime
    - core           # Per CPU core usage
    - diskio         # Disk IO
    - filesystem     # File system usage for each mountpoint
    - fsstat         # File system summary metrics
    - raid           # Raid
    - socket         # Sockets and connection info (linux only)
  enabled: true
  period: 10s
  processes: ['.*']

  # Configure the metric types that are included by these metricsets.
  cpu.metrics:  ["percentages"]  # The other available options are normalized_percentages and ticks.
  core.metrics: ["percentages"]  # The other available option is ticks.

- module: rabbitmq
  metricsets: ["node", "queue", "connection"]
  enabled: true
  period: 10s
  hosts: ["localhost:15672"]

- module: nginx
  metricsets: ["stubstatus"]
  enabled: true
  period: 10s
  # Nginx hosts
  hosts: ["http://host.docker.internal"]
  # Path to server status. Default server-status
  server_status_path: "nginx_status"
